[variables]
NIXPACKS_METADATA = 'python'
PYTHONUNBUFFERED = '1'
[phases.install]
dependsOn = ['setup']
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt && pip install -e ./ChatGPTBot']
cacheDirectories = ['/root/.cache/pip']
paths = ['/opt/venv/bin']

[phases.setup]
nixPkgs = [
    'python310',
    'gcc',
]
nixLibs = [
    'zlib',
    'stdenv.cc.cc.lib',
]

[start]
cmd = "uvicorn che_bot_api:app --host 0.0.0.0 --port $PORT"